# Generated by Django 5.2.3 on 2025-07-01 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alter_resumescorehistory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumescorehistory',
            name='jd_file',
            field=models.FileField(blank=True, null=True, upload_to='job_descriptions/'),
        ),
        migrations.AddField(
            model_name='resumescorehistory',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
    ]
